/*
 * This file was automatically generated by EvoSuite
 * Tue Sep 22 18:59:13 GMT 2026
 */

package evosuiteTests;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.evosuite.runtime.System;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;
import org.junit.Test;
import org.junit.runner.RunWith;

import ar.edu.unrc.game2048.Board;
import ar.edu.unrc.game2048.Cell;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Board_ESTest extends Board_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Board board0 = new Board(53);
      int int0 = Board.WINNING_VALUE;
      int int1 = (-5);
      int int2 = 2924;
      board0.hasEmptyCells();
      // Undeclared exception!
      board0.isLosingBoard();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Board board0 = new Board(40, 53);
      board0.moveUp();
      board0.getScore();
      board0.moveDown();
      // Undeclared exception!
      board0.hasEmptyCells();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Board board0 = new Board();
      board0.moveRight();
      board0.isFull();
      Object object0 = new Object();
      board0.equals(board0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Board board0 = new Board(49, 49);
      board0.repOk();
      board0.moveUp();
      board0.repOk();
      board0.getSize();
      // Undeclared exception!
      board0.moveRight();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Random.setNextRandom(2);
      Board board0 = new Board();
      Board board1 = new Board(board0);
      board0.moveRight();
      board1.equals(board0);
      board1.getSize();
      board0.moveRight();
      System.setCurrentTimeMillis((-90L));
      board1.getSize();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Board board0 = new Board(39, 39);
      board0.isLosingBoard();
      board0.moveLeft();
      // Undeclared exception!
      board0.moveDown();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Board board0 = new Board();
      board0.clearBoard();
      board0.isLosingBoard();
      board0.hashCode();
      board0.moveUp();
      Board board1 = new Board();
      boolean boolean0 = board0.equals(board1);
      assertEquals(0, board0.tileAmount());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      int int0 = 0;
      Board.Position board_Position0 = new Board.Position(0, (-1063));
      Board.Position board_Position1 = new Board.Position(0, 0);
      board_Position1.toString();
      board_Position0.equals(board_Position1);
      Board board0 = new Board(4);
      board0.getSize();
      board0.hashCode();
      board_Position1.toString();
      Object object0 = new Object();
      board_Position1.equals(object0);
      int int1 = (-3037);
      // Undeclared exception!
      try { 
        board0.getCell((-3037), (-1));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-3037, -1) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(0, 0);
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      String string0 = board_Position0.toString();
      assertEquals("(0, 0)", string0);
      
      Board.Position board_Position1 = new Board.Position(0, 0);
      boolean boolean0 = board_Position0.equals(board_Position1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Board board0 = new Board(2);
      board0.toString();
      // Undeclared exception!
      try { 
        board0.clearBoard();
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 2) is out of bounds for board size 2
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(0, 0);
      Board board0 = new Board();
      board0.isLosingBoard();
      Board board1 = new Board(board0);
      board_Position0.toString();
      board1.isLosingBoard();
      board_Position0.toString();
      // Undeclared exception!
      try { 
        board1.getCell(0, 4);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 4) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Board board0 = new Board(3, (-537));
      board0.isLosingBoard();
      board0.getCell(1, 0);
      board0.moveLeft();
      // Undeclared exception!
      try { 
        board0.getCell(0, (-4608));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, -4608) is out of bounds for board size 3
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.setCell(0, 0, (Cell) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cell cannot be null
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Board board0 = new Board(2);
      board0.getEmptyPositions();
      board0.moveUp();
      board0.isFull();
      board0.moveRight();
      board0.moveDown();
      // Undeclared exception!
      try { 
        board0.getCell((-2967), 2);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-2967, 2) is out of bounds for board size 2
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(2063, 3128);
      Board.Position board_Position1 = new Board.Position((-1311), 0);
      boolean boolean0 = board_Position0.equals(board_Position1);
      assertEquals((-1311), board_Position1.row);
      assertEquals(3128, board_Position0.col);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.getCell(0, 961);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 961) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-664), 0);
      Board.Position board_Position1 = new Board.Position(693, (-664));
      boolean boolean0 = board_Position0.equals(board_Position1);
      assertEquals((-664), board_Position1.col);
      assertFalse(boolean0);
      assertEquals(693, board_Position1.row);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Board board0 = new Board();
      board0.clearBoard();
      board0.hasEmptyCells();
      board0.moveRight();
      board0.moveRight();
      board0.clearBoard();
      board0.moveDown();
      board0.tileAmount();
      board0.getSize();
      Board.Direction.values();
      board0.moveLeft();
      Cell cell0 = Cell.EMPTY;
      // Undeclared exception!
      try { 
        board0.getCell(2894, 4);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (2894, 4) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Board board0 = new Board();
      board0.isLosingBoard();
      board0.tileAmount();
      Cell cell0 = board0.getCell(0, 1);
      board0.setCell(2, 2, cell0);
      Object object0 = new Object();
      board0.equals(object0);
      assertEquals(4, board0.getSize());
      assertEquals(2, board0.tileAmount());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = new Board(board0);
      board1.moveRight();
      assertEquals(4, board1.getScore());
      
      board0.getScore();
      board0.equals((Object) null);
      assertEquals(4, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      int int0 = 925;
      Board board0 = new Board(925);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Board board0 = new Board();
      board0.toString();
      board0.getEmptyPositions();
      board0.hashCode();
      board0.hashCode();
      board0.moveDown();
      board0.tileAmount();
      board0.clearBoard();
      board0.moveLeft();
      board0.hashCode();
      board0.hasEmptyCells();
      int int0 = (-2745);
      Cell cell0 = null;
      // Undeclared exception!
      try { 
        board0.setCell(3, (-2745), (Cell) null);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (3, -2745) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Board board0 = new Board(4);
      board0.toString();
      Board board1 = new Board(board0);
      assertEquals(4, board1.getSize());
      
      board1.repOk();
      String string0 = board1.toString();
      assertEquals("Score: 0\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|    2|    2|     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n", string0);
      assertTrue(board1.equals((Object)board0));
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Board board0 = new Board();
      board0.getSize();
      board0.moveRight();
      Board.Position board_Position0 = new Board.Position(4, 4);
      board_Position0.toString();
      board0.hashCode();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.equals(board0);
      board0.repOk();
      assertEquals(4, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.getCell((-6670), 3);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-6670, 3) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(2, 2);
      board_Position0.toString();
      board_Position0.toString();
      Board board0 = null;
      try {
        board0 = new Board((Board) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = new Board(board0);
      board1.isLosingBoard();
      board1.hashCode();
      board1.getEmptyPositions();
      board1.isWinningBoard();
      board0.repOk();
      board1.moveLeft();
      board0.hasEmptyCells();
      board1.isFull();
      board1.hashCode();
      // Undeclared exception!
      try { 
        board1.getCell(2048, 2048);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (2048, 2048) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Board board0 = new Board(3493, 3493);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Board board0 = new Board();
      board0.moveLeft();
      boolean boolean0 = board0.hasEmptyCells();
      assertEquals(4, board0.getScore());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((-895), (-895));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -895
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Board board0 = new Board(4);
      Object object0 = new Object();
      board0.equals(object0);
      board0.moveUp();
      boolean boolean0 = board0.hasEmptyCells();
      assertEquals(3, board0.tileAmount());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      int int0 = 1;
      int int1 = (-2340);
      Board board0 = null;
      try {
        board0 = new Board(1, (-2340));
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Board is full, no empty positions available.
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board(1);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Board is full, no empty positions available.
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Board board0 = new Board(2, 2);
      int int0 = board0.tileAmount();
      assertFalse(board0.isWinningBoard());
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((-292));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -292
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((-1483));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -1483
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.repOk();
      boolean boolean1 = board0.equals((Object) null);
      assertEquals(2, board0.tileAmount());
      assertFalse(boolean1 == boolean0);
      assertEquals(4, board0.getSize());
      
      Board.Position board_Position0 = new Board.Position(0, 0);
      boolean boolean2 = board_Position0.equals((Object) null);
      assertFalse(boolean2 == boolean0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      int int0 = 0;
      Board board0 = null;
      try {
        board0 = new Board(0, 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: 0
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board(1, 1);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Board is full, no empty positions available.
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      int int0 = (-1338);
      Board board0 = null;
      try {
        board0 = new Board((-1338), (-1338));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -1338
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Board board0 = new Board();
      board0.getSize();
      Board board1 = new Board(board0);
      board1.getEmptyPositions();
      board1.hashCode();
      assertTrue(board1.equals((Object)board0));
      
      board1.moveUp();
      board1.equals(board0);
      System.setCurrentTimeMillis(4);
      board0.getSize();
      int int0 = board0.tileAmount();
      assertFalse(board0.equals((Object)board1));
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Board board0 = new Board();
      board0.moveDown();
      board0.moveRight();
      board0.tileAmount();
      board0.hasEmptyCells();
      board0.moveRight();
      board0.getScore();
      board0.getEmptyPositions();
      board0.isLosingBoard();
      board0.tileAmount();
      board0.moveDown();
      board0.repOk();
      board0.clearBoard();
      board0.clearBoard();
      board0.hasEmptyCells();
      board0.toString();
      board0.moveUp();
      // Undeclared exception!
      try { 
        board0.getCell(4, 3);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (4, 3) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Board board0 = new Board(1943);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      int int0 = 0;
      Board.Position board_Position0 = new Board.Position(0, (-1063));
      Board.Position board_Position1 = new Board.Position(0, 1);
      board_Position1.toString();
      board_Position0.equals(board_Position1);
      Board board0 = new Board(4);
      board0.getSize();
      board0.hashCode();
      board0.repOk();
      board_Position1.toString();
      Object object0 = new Object();
      board_Position1.equals(object0);
      int int1 = (-3037);
      // Undeclared exception!
      try { 
        board0.getCell((-3037), (-1));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-3037, -1) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      int int0 = 143;
      Board board0 = new Board(143);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Board board0 = new Board();
      int int0 = 1;
      int int1 = (-30);
      // Undeclared exception!
      try { 
        board0.getCell(1, (-30));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (1, -30) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      int int0 = 2;
      Board board0 = new Board(2);
      board0.isLosingBoard();
      board0.hashCode();
      Board board1 = new Board(board0);
      board1.isFull();
      board0.repOk();
      int int1 = (-1194);
      Board.Position board_Position0 = new Board.Position((-1194), (-1358));
      board_Position0.toString();
      board1.hasEmptyCells();
      board0.hashCode();
      board0.moveDown();
      board1.getEmptyPositions();
      board1.isFull();
      board0.isWinningBoard();
      Board board2 = null;
      try {
        board2 = new Board((-1194), (-1358));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -1194
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      int int0 = 5771;
      int int1 = 0;
      Board board0 = new Board(5771, 0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Board board0 = new Board();
      board0.clearBoard();
      Board board1 = new Board(4, 2048);
      board0.isFull();
      board0.moveLeft();
      board1.getEmptyPositions();
      board1.moveRight();
      Board board2 = new Board(board1);
      board2.hasEmptyCells();
      board0.hashCode();
      board2.moveRight();
      board1.hashCode();
      board1.hashCode();
      board0.hashCode();
      board0.moveDown();
      board0.isWinningBoard();
      board1.toString();
      board1.toString();
      board0.equals("Score: 0\n+-----+-----+-----+-----+\n|     |     |     |    2|\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|    4|     |     |    2|\n+-----+-----+-----+-----+\n");
      // Undeclared exception!
      try { 
        board0.getCell(1, 4);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (1, 4) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Cell cell0 = Cell.EMPTY;
      Board board0 = null;
      try {
        board0 = new Board((-167));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -167
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }
}
