/*
 * This file was automatically generated by EvoSuite
 * Mon Sep 21 18:19:22 GMT 2026
 */

package ar.edu.unrc.game2048;

import java.util.Set;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class Board_ESTest extends Board_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-1915), 4);
      board_Position0.toString();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(0, 0);
      Board.Position board_Position1 = new Board.Position(0, 1585);
      board_Position0.equals(board_Position1);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(2048, 4);
      Board.Position board_Position1 = new Board.Position(2048, (-2248));
      board_Position0.equals(board_Position1);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-1547), 1497);
      Board.Position board_Position1 = new Board.Position(1497, 1497);
      board_Position0.equals(board_Position1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Board board0 = new Board(2, 4224);
      board0.toString();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Board board0 = new Board(2);
      board0.hashCode();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.getCell(1, 2048);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (1, 2048) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.getCell(418, 2048);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (418, 2048) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Board board0 = new Board();
      board0.clearBoard();
      board0.tileAmount();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Board board0 = new Board();
      board0.clearBoard();
      board0.moveUp();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Board board0 = new Board();
      board0.moveLeft();
      board0.moveRight();
      board0.moveDown();
      board0.moveUp();
      board0.moveRight();
      board0.moveRight();
      board0.moveLeft();
      board0.moveUp();
      board0.moveDown();
      board0.moveDown();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Board board0 = new Board();
      board0.moveLeft();
      board0.getScore();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Board board0 = new Board(2);
      board0.moveUp();
      board0.moveRight();
      board0.moveLeft();
      board0.getEmptyPositions();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Board board0 = new Board(60);
      // Undeclared exception!
      board0.hasEmptyCells();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((Board) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Board board0 = new Board(1639, 1639);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Board board0 = new Board(1585);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board(1);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Board is full, no empty positions available.
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = new Board(board0);
      assertEquals(2, board1.tileAmount());
      
      board1.clearBoard();
      boolean boolean0 = board1.equals(board0);
      assertEquals(0, board1.tileAmount());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Board board0 = new Board();
      board0.moveRight();
      Board board1 = new Board();
      board0.equals(board1);
      assertEquals(4, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Board board0 = new Board();
      board0.equals(board0);
      assertEquals(4, board0.getSize());
      assertEquals(2, board0.tileAmount());
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.hasEmptyCells();
      assertTrue(boolean0);
      assertEquals(2, board0.tileAmount());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Board board0 = new Board(2);
      board0.moveUp();
      board0.moveRight();
      board0.moveLeft();
      boolean boolean0 = board0.hasEmptyCells();
      assertEquals(4, board0.tileAmount());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Board board0 = new Board();
      Cell cell0 = Cell.EMPTY;
      board0.setCell(3, 2, cell0);
      assertEquals(0, board0.getScore());
      assertFalse(board0.isWinningBoard());
      assertEquals(2, board0.tileAmount());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = new Board(board0);
      boolean boolean0 = board1.equals(board0);
      assertEquals(4, board1.getSize());
      assertTrue(boolean0);
      assertEquals(2, board1.tileAmount());
      assertEquals(0, board1.getScore());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Board board0 = new Board();
      int int0 = board0.getSize();
      assertEquals(2, board0.tileAmount());
      assertEquals(4, int0);
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(4, 4);
      boolean boolean0 = board_Position0.equals(", ");
      assertFalse(boolean0);
      assertEquals(4, board_Position0.row);
      assertEquals(4, board_Position0.col);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(4, 4);
      Board.Position board_Position1 = new Board.Position(4, 4);
      boolean boolean0 = board_Position0.equals(board_Position1);
      assertEquals(4, board_Position1.row);
      assertTrue(boolean0);
      assertEquals(4, board_Position1.col);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(4, 4);
      boolean boolean0 = board_Position0.equals(board_Position0);
      assertEquals(4, board_Position0.row);
      assertTrue(boolean0);
      assertEquals(4, board_Position0.col);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(4, 4);
      boolean boolean0 = board_Position0.equals((Object) null);
      assertEquals(4, board_Position0.col);
      assertFalse(boolean0);
      assertEquals(4, board_Position0.row);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Board board0 = new Board();
      board0.clearBoard();
      boolean boolean0 = board0.moveRight();
      assertEquals(0, board0.tileAmount());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Board board0 = new Board(2);
      int int0 = board0.tileAmount();
      assertFalse(board0.isWinningBoard());
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Board board0 = new Board();
      Set<Board.Position> set0 = board0.getEmptyPositions();
      boolean boolean0 = board0.equals(set0);
      assertEquals(14, set0.size());
      assertEquals(0, board0.getScore());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Board board0 = new Board(4);
      board0.equals((Object) null);
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertEquals(2, board0.tileAmount());
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board(1, 1497);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Board is full, no empty positions available.
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Board board0 = new Board(2);
      board0.moveUp();
      board0.moveDown();
      board0.moveLeft();
      boolean boolean0 = board0.isFull();
      assertEquals(4, board0.tileAmount());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.isFull();
      assertFalse(boolean0);
      assertEquals(2, board0.tileAmount());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Board board0 = new Board(2);
      board0.moveUp();
      board0.moveRight();
      board0.moveLeft();
      boolean boolean0 = board0.isLosingBoard();
      assertEquals(4, board0.getScore());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Board board0 = new Board(2);
      boolean boolean0 = board0.isWinningBoard();
      assertEquals(2, board0.tileAmount());
      assertFalse(boolean0);
      assertEquals(2, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Board board0 = new Board(2);
      board0.moveUp();
      board0.moveDown();
      board0.moveLeft();
      boolean boolean0 = board0.isLosingBoard();
      assertEquals(4, board0.getScore());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Board board0 = new Board(2, (-821));
      board0.isLosingBoard();
      assertEquals(2, board0.tileAmount());
      assertEquals(2, board0.getSize());
      assertFalse(board0.isWinningBoard());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.getCell(1, (-4061));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (1, -4061) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Board board0 = new Board();
      Cell cell0 = new Cell(0);
      // Undeclared exception!
      try { 
        board0.setCell(4, 2565, cell0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (4, 2565) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.getCell((-2271), 22);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-2271, 22) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.setCell(0, 0, (Cell) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cell cannot be null
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Board board0 = new Board(2, (-821));
      // Undeclared exception!
      try { 
        board0.clearBoard();
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 2) is out of bounds for board size 2
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((-285), 1653);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -285
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((-2046));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -2046
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Board board0 = new Board(2);
      boolean boolean0 = board0.moveDown();
      assertEquals(4, board0.getScore());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Board board0 = new Board(2);
      boolean boolean0 = board0.moveLeft();
      assertFalse(boolean0);
      assertEquals(2, board0.tileAmount());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Board board0 = new Board(2);
      boolean boolean0 = board0.repOk();
      assertTrue(boolean0);
      assertEquals(2, board0.tileAmount());
      assertEquals(2, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Board board0 = new Board();
      int int0 = board0.getScore();
      assertEquals(2, board0.tileAmount());
      assertEquals(4, board0.getSize());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Board board0 = new Board();
      board0.moveUp();
      board0.getCell(0, 0);
      assertEquals(3, board0.tileAmount());
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Board board0 = new Board();
      Cell cell0 = board0.getCell(0, 0);
      assertEquals(".", cell0.toString());
      assertEquals(4, board0.getSize());
  }
}
