/*
 * This file was automatically generated by EvoSuite
 * Mon Sep 21 11:37:46 GMT 2026
 */

package evosuiteTests;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;
import org.junit.Test;
import org.junit.runner.RunWith;

import ar.edu.unrc.game2048.Board;
import ar.edu.unrc.game2048.Cell;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Board_ESTest extends Board_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Board board0 = new Board();
      board0.isLosingBoard();
      Object object0 = new Object();
      board0.equals(object0);
      board0.moveLeft();
      board0.moveUp();
      board0.moveRight();
      board0.toString();
      board0.getScore();
      Board.Position board_Position0 = new Board.Position(1, 2048);
      board_Position0.equals(board_Position0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(1, (-2216));
      Board board0 = new Board();
      board0.equals(board_Position0);
      Board.Position board_Position1 = new Board.Position(2048, 2048);
      board_Position0.equals(board_Position1);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      int int0 = 56;
      Board board0 = new Board(56, 56);
      board0.hashCode();
      board0.isFull();
      // Undeclared exception!
      board0.hasEmptyCells();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Board board0 = new Board();
      board0.hasEmptyCells();
      board0.getSize();
      board0.clearBoard();
      board0.isLosingBoard();
      board0.moveDown();
      board0.isWinningBoard();
      board0.getSize();
      board0.repOk();
      board0.getSize();
      Board.Direction.values();
      Board board1 = new Board(4, 4);
      board0.equals(board1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Board board0 = new Board();
      board0.hasEmptyCells();
      board0.getSize();
      board0.clearBoard();
      board0.isLosingBoard();
      board0.moveDown();
      board0.isWinningBoard();
      board0.getSize();
      board0.repOk();
      board0.getSize();
      Board.Direction.values();
      board0.equals(board0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Board board0 = new Board();
      board0.moveDown();
      board0.toString();
      board0.clearBoard();
      board0.moveUp();
      board0.moveUp();
      board0.toString();
      board0.repOk();
      board0.clearBoard();
      board0.getSize();
      board0.repOk();
      board0.toString();
      board0.getScore();
      int int0 = 0;
      Cell cell0 = new Cell(4);
      board0.setCell(0, 0, cell0);
      Cell cell1 = null;
      board0.getEmptyPositions();
      // Undeclared exception!
      try { 
        board0.setCell(503, (-15), (Cell) null);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (503, -15) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-1), (-268));
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      Board board0 = new Board();
      board0.moveRight();
      board0.moveDown();
      board0.repOk();
      board0.equals("(-1, -268)");
      board0.repOk();
      board0.equals((Object) null);
      board0.clearBoard();
      board0.isLosingBoard();
      board0.moveDown();
      Cell cell0 = new Cell(4);
      // Undeclared exception!
      try { 
        board0.setCell((-1), 17, cell0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-1, 17) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Board board0 = new Board();
      board0.moveRight();
      board0.moveDown();
      board0.repOk();
      board0.repOk();
      board0.equals((Object) null);
      board0.clearBoard();
      board0.isLosingBoard();
      board0.moveDown();
      Cell cell0 = new Cell(4);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Board board0 = new Board();
      board0.moveLeft();
      int int0 = 1;
      // Undeclared exception!
      try { 
        board0.setCell(1, 0, (Cell) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cell cannot be null
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      int int0 = 4;
      Board board0 = new Board(4);
      board0.repOk();
      Board board1 = new Board(board0);
      board1.moveUp();
      board1.moveLeft();
      board1.moveLeft();
      board1.equals(board0);
      Board.Direction.values();
      board0.toString();
      board1.moveUp();
      board0.isWinningBoard();
      board0.isLosingBoard();
      board0.clearBoard();
      board0.hashCode();
      board0.moveRight();
      board1.repOk();
      // Undeclared exception!
      try { 
        board0.getCell(4, (-604));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (4, -604) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Board board0 = new Board();
      board0.repOk();
      board0.moveUp();
      board0.getEmptyPositions();
      board0.toString();
      board0.hashCode();
      board0.moveRight();
      board0.toString();
      int int0 = 0;
      board0.getCell(0, 0);
      board0.moveRight();
      board0.getScore();
      board0.hasEmptyCells();
      board0.moveUp();
      board0.isLosingBoard();
      // Undeclared exception!
      try { 
        board0.getCell(0, 2115);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 2115) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Board board0 = new Board(2);
      board0.hashCode();
      Board board1 = new Board(board0);
      board1.equals(board0);
      board1.isWinningBoard();
      board0.isFull();
      board0.equals(board1);
      // Undeclared exception!
      try { 
        board0.getCell(2048, 4);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (2048, 4) is out of bounds for board size 2
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Board board0 = new Board();
      board0.hashCode();
      board0.moveLeft();
      board0.moveDown();
      board0.clearBoard();
      board0.clearBoard();
      board0.repOk();
      board0.moveRight();
      board0.toString();
      board0.clearBoard();
      board0.tileAmount();
      board0.hasEmptyCells();
      board0.moveRight();
      board0.clearBoard();
      board0.hasEmptyCells();
      int int0 = 2668;
      int int1 = 2;
      Cell cell0 = new Cell(4);
      Cell cell1 = Cell.EMPTY;
      // Undeclared exception!
      try { 
        cell0.mergeWith(cell1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot merge cells: 4 and .
         //
         verifyException("ar.edu.unrc.game2048.Cell", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      int int0 = 1;
      Board board0 = null;
      try {
        board0 = new Board(1);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Board is full, no empty positions available.
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = new Board(board0);
      board0.moveLeft();
      Board board2 = new Board(board1);
      board0.isWinningBoard();
      board2.getEmptyPositions();
      Board.Position board_Position0 = new Board.Position(4, 4);
      board1.equals(board_Position0);
      board2.moveLeft();
      board_Position0.toString();
      board1.getScore();
      board1.moveRight();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Board board0 = new Board(3, 995);
      board0.tileAmount();
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Board board0 = new Board(35, 35);
      board0.repOk();
      board0.clearBoard();
      board0.getSize();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Board board0 = new Board(2, (-555));
      Board board1 = new Board(board0);
      board1.equals(board0);
      Board.Direction.values();
      board0.hasEmptyCells();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Board board0 = new Board();
      board0.isLosingBoard();
      board0.getCell(1, 0);
      board0.moveDown();
      board0.repOk();
      board0.repOk();
      board0.isWinningBoard();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      int int0 = 0;
      Board board0 = null;
      try {
        board0 = new Board(0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: 0
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(2459, 2459);
      Board board0 = new Board();
      board_Position0.equals(board0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Board board0 = new Board();
      board0.clearBoard();
      board0.moveRight();
      board0.isFull();
      board0.moveDown();
      board0.clearBoard();
      Board.Direction.values();
      board0.clearBoard();
      board0.hasEmptyCells();
      board0.moveUp();
      board0.moveDown();
      board0.isLosingBoard();
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      int int0 = 35;
      Board board0 = new Board(35);
      board0.moveRight();
      board0.toString();
      board0.moveRight();
      // Undeclared exception!
      board0.moveUp();
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((Board) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      int int0 = 1;
      Board board0 = null;
      try {
        board0 = new Board(1, 0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Board is full, no empty positions available.
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board(1, 1);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Board is full, no empty positions available.
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Board board0 = new Board();
      board0.moveLeft();
      Cell cell0 = new Cell(0);
      // Undeclared exception!
      try { 
        board0.setCell(669, 669, cell0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (669, 669) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Board board0 = new Board(76);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Board board0 = new Board();
      board0.moveRight();
      board0.toString();
      board0.clearBoard();
      board0.moveUp();
      board0.isLosingBoard();
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Board board0 = new Board();
      board0.hashCode();
      board0.moveDown();
      board0.repOk();
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-1), (-1));
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.equals((Object) null);
      board_Position0.toString();
      int int0 = 2;
      board_Position0.toString();
      Board board0 = new Board(2, (-1453));
      board0.moveRight();
      board0.moveUp();
      board_Position0.toString();
      // Undeclared exception!
      try { 
        board0.getCell((-590), (-1));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-590, -1) is out of bounds for board size 2
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Board board0 = new Board(2, 2);
      board0.moveLeft();
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Board.Direction.values();
      Board board0 = new Board();
      Board board1 = new Board(board0);
      board1.getScore();
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Board board0 = new Board();
      Cell cell0 = board0.getCell(2, 0);
      // Undeclared exception!
      try { 
        board0.setCell(2, 901, cell0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (2, 901) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Board board0 = new Board(4);
      Board.Direction.values();
      Board.Position board_Position0 = new Board.Position(4, 4);
      board0.equals(board_Position0);
      board0.hasEmptyCells();
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Board board0 = new Board(2, 2);
      // Undeclared exception!
      try { 
        board0.clearBoard();
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 2) is out of bounds for board size 2
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      int int0 = 0;
      Board board0 = null;
      try {
        board0 = new Board((-1872), 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -1872
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      int int0 = 59;
      Board board0 = new Board(4530, 59);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-61), 0);
      Board board0 = new Board();
      board_Position0.toString();
      // Undeclared exception!
      try { 
        board0.getCell((-61), 4);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-61, 4) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.getCell((-75), (-75));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-75, -75) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((-721), (-721));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -721
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(3, 4);
      board_Position0.toString();
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Board.Direction.values();
      Board.Position board_Position0 = new Board.Position(2234, 2234);
      Board.Position board_Position1 = new Board.Position(2234, 2048);
      board_Position0.equals(board_Position1);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      int int0 = 2071;
      Board.Position board_Position0 = new Board.Position((-2349), 2071);
      board_Position0.toString();
      Board board0 = new Board();
      board_Position0.equals(board0);
      board0.moveDown();
      Cell cell0 = new Cell(2);
      // Undeclared exception!
      try { 
        board0.getCell(2071, 11);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (2071, 11) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-2197), 0);
      Board board0 = null;
      try {
        board0 = new Board((-4198));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -4198
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Board board0 = new Board();
      board0.isLosingBoard();
      Object object0 = new Object();
      board0.clearBoard();
      board0.equals(object0);
      board0.moveLeft();
      board0.moveUp();
      board0.moveRight();
      board0.toString();
      board0.getScore();
      Board.Position board_Position0 = new Board.Position(1, 2048);
      board_Position0.equals((Object) null);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Board board0 = new Board();
      int int0 = (-923);
      int int1 = 354;
      int int2 = 457;
      // Undeclared exception!
      try { 
        board0.getCell(0, 457);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 457) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Board board0 = new Board();
      board0.hasEmptyCells();
      board0.getSize();
      board0.clearBoard();
      board0.isLosingBoard();
      board0.moveDown();
      board0.isWinningBoard();
      board0.getSize();
      board0.repOk();
      board0.getSize();
      Board.Direction.values();
      Board board1 = new Board(board0);
      board1.getEmptyPositions();
      board0.equals(board1);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((-1419), (-1419));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -1419
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      int int0 = 96;
      Board board0 = new Board(96, 96);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Board.Direction.values();
      Board board0 = null;
      try {
        board0 = new Board((-1298));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -1298
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Board board0 = new Board();
      board0.isFull();
      board0.moveDown();
      board0.moveDown();
      board0.repOk();
      board0.moveRight();
      board0.isLosingBoard();
      board0.toString();
      board0.getEmptyPositions();
      board0.hashCode();
      board0.getSize();
      board0.hasEmptyCells();
      board0.tileAmount();
      board0.hashCode();
      boolean boolean0 = board0.moveDown();
      assertEquals(4, board0.getScore());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Board board0 = new Board();
      board0.repOk();
      board0.moveDown();
      board0.moveRight();
      board0.tileAmount();
      board0.isFull();
      Board.Direction.values();
      board0.getEmptyPositions();
      board0.isFull();
      // Undeclared exception!
      try { 
        board0.setCell(3, (-1566), (Cell) null);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (3, -1566) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }
}
